[package]
name = "dm-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
structopt = "0.3.26"
xxdk = { version = "0.1.0", path = "../xxdk" }
